version: '3.8'

services:
  # Nasza aplikacja (Backend)
  api:
    build: ./backend
    container_name: nauka_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app:z
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/nauka_db
    depends_on:
      - db

  # Baza Danych
  db:
    image: postgres:15-alpine
    container_name: nauka_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nauka_db
    ports:
      - "5432:5432"

  # Podgląd Bazy Danych (opcjonalnie, dla wygody developera)
  pgadmin:
    image: dpage/pgadmin4
    container_name: nauka_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
