create table public."user" (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  is_active boolean not null default true
);

create table public.deck (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  user_id uuid not null references public."user"(id) on delete cascade
);

create table public.question (
  id bigint generated by default as identity primary key,
  content text not null,
  deck_id bigint not null references public.deck(id) on delete cascade
);

create table public.answer (
  id bigint generated by default as identity primary key,
  content text not null,
  is_correct boolean not null default false,
  question_id bigint not null references public.question(id) on delete cascade
);

create table public.quizsession (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public."user"(id) on delete cascade,
  deck_id bigint not null references public.deck(id) on delete cascade,
  queue_str text not null default '',
  is_active boolean not null default true,
  created_at timestamp without time zone not null default timezone('utc', now()),
  total_time_seconds integer not null default 0,
  last_activity timestamp without time zone not null default timezone('utc', now()),
  is_paused boolean not null default false
);

create table public.todo (
  id bigint generated by default as identity primary key,
  text text not null,
  done boolean not null default false,
  user_id uuid not null references public."user"(id) on delete cascade
);

create table public.note (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  created_at timestamp without time zone not null default timezone('utc', now()),
  user_id uuid not null references public."user"(id) on delete cascade
);

create table public.link (
  id bigint generated by default as identity primary key,
  title text not null,
  url text not null,
  category text not null default 'Inne',
  user_id uuid not null references public."user"(id) on delete cascade
);

create index deck_user_id_idx on public.deck(user_id);
create index quizsession_user_id_idx on public.quizsession(user_id);
create index todo_user_id_idx on public.todo(user_id);
create index note_user_id_idx on public.note(user_id);
create index link_user_id_idx on public.link(user_id);

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public."user" (id, email)
  values (new.id, coalesce(new.email, ''))
  on conflict (id) do update set email = excluded.email, is_active = true;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert or update of email on auth.users
  for each row execute procedure public.handle_new_auth_user();

alter table public."user" enable row level security;
alter table public.deck enable row level security;
alter table public.question enable row level security;
alter table public.answer enable row level security;
alter table public.quizsession enable row level security;
alter table public.todo enable row level security;
alter table public.note enable row level security;
alter table public.link enable row level security;
